project:
  type: website
  output-dir: docs

website:
  title: "Economy Review 2025"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/CrumpLab/quartoCourseBlog
      - icon: twitter
        href: https://twitter.com/MattCrumpLab
format:
  html:
    theme: lumen
    css: styles.css

editor: visual

